name: Build & Push Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akaidmaru
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        run: |
          docker build \
          --build-arg VITE_API_URL=${{ env.VITE_API_URL }} \
          -t ghcr.io/akaidmaru/digitalhouse-proyectointegrador-team1-petcare:latest .
          docker push ghcr.io/akaidmaru/digitalhouse-proyectointegrador-team1-petcare:latest

      - name: Trigger Infra Deployment
        uses: actions/github-script@v6
        if: success()
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'akaidmaru',
              repo: 'infra',
              workflow_id: 'deploy-prod.yml',
              ref: 'main',
            });
