name: Build & Push Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (como akaidmaru)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akaidmaru
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push
        run: |
          docker build \
          --build-arg VITE_API_URL=${{ env.VITE_API_URL }} \
          -t ghcr.io/akaidmaru/digitalhouse-proyectointegrador-team1-petcare:latest .
          docker push ghcr.io/akaidmaru/digitalhouse-proyectointegrador-team1-petcare:latest

